### ISSUE TITLE
Неправильное отображение тегов

### ISSUE THREAD

**Issue by coursar** [ayrat-l/ozon-web#3]
https://github.com/ayrat-l/ozon-web/blob/01be30d95740438a7bd7b853926617635babf058/app/templates/index.html#L31

Теги должны отображаться так:
#поезд, #любовь, #толстой

А не вот так:
['#поезд', '#любовь', '#толстой']

**Comment by ayrat-l** [comment]
https://github.com/ayrat-l/ozon-web/blob/9ca665a95e0f96f998d60db589e45f7a2f709f0a/app/ozon.py#L11-L14

Вот здесь надо что-то сделать да? Распаковку списка?

**Comment by ayrat-l** [comment]
Сделано. 

Fixed#3 сделаю в след раз =)
